[build]
  publish = "dist/"
  command = "pnpm run build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
 from = "/feeds/all.xml"
 to = "/feed.xml"
